### ISSUE TITLE
Change title to macOS

### ISSUE THREAD

**Issue by herrbischoff** [herrbischoff/awesome-macos-command-line#117]
As soon as Sierra is officially released, change the name to `awesome-macos-command-line`.

**Update:** Lowest priority for now. I'm getting to it eventually but not right now.

**Comment by napcae** [comment]
@herrbischoff it's released;)

**Comment by jdickey** [comment]
Ummm, I gave the idea a thumbs-down *because*

1. There are still a *lot* of people who haven't upgraded/won't upgrade before 10.12.2 is out (at least); and
2. Renaming it from a long-used name would encourage new people to expect that the list was Sierra-specific when it's really not.

**Comment by herrbischoff** [comment]
@jdickey: A valid and interesting point. I am not particularly partial to jumping on any new development. Long term however, this makes sense as Apple has officially renamed Mac OS X to macOS, for better or worse.

**Comment by napcae** [comment]
@jdickey Almost a [third on Sierra, 40% on El Capitan](https://www.gosquared.com/global/mac/sierra/#beta). I think it's safe to say that we can ignore Yosemite, since command line users are power users and have updated systems.

**Comment by jdickey** [comment]
@napcae. Right. We're an El Capitan shop and have no expectation to even touch Sierra until 10.12.2+ reduces the support panic to normal levels *and* all our critical tools support it. Neither of those conditions yet apply. Did they change the name of El Capitan and we just didn't notice? *That* was my point.

**Comment by herrbischoff** [comment]
I wonder why the name change appears to be such a thing of importance for some people. It's still OS X, it's just marketing. Gonna get to it later.

**Comment by herrbischoff** [comment]
As that product name is here to stay, this was changed just now. The old repository name redirects to the new name.
