### ISSUE TITLE
Disabling Media Keys Not Working as of 10.12.4

### ISSUE THREAD

**Issue by PhilipTrauner** [herrbischoff/awesome-macos-command-line#134]
As of macOS 10.12.4 SIP has to be disengaged to disable the iTunes media keys.

```bash
> launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist
/System/Library/LaunchAgents/com.apple.rcd.plist: Operation not permitted while System Integrity Protection is engaged
```

**Comment by herrbischoff** [comment]
Thanks for letting me know. I will update the entry to reflect that.

**Comment by m3at** [comment]
On macOS 10.11.6 with SIP disengaged I get a "Could not find specified service":
```
% launchctl unload /System/Library/LaunchAgents/com.apple.rcd.plist
/System/Library/LaunchAgents/com.apple.rcd.plist: Could not find specified service
```

**Comment by zachleat** [comment]
Since I don’t use iTunes at all, I had luck with setting permissions on the application to “No Access” in the Finder ⌘+I popup

![image](https://cloud.githubusercontent.com/assets/39355/25049053/62446742-2105-11e7-9b1f-df03eb75ba74.png)
