### ISSUE TITLE
Extensions to Dock Command Lines

### ISSUE THREAD

**Issue by Eramono** [herrbischoff/awesome-macos-command-line#172]
I don't know whether this is a common knowledge or not.
I hope it could be helpful.

**Add a Small Space**
(Modification of "Add a Space")
`defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="small-spacer-tile";}' && \
killall Dock`

**Add a Stack Folder with no name and small space**
(Modification of "Add a Stack with Recent Applications")
`defaults write com.apple.dock persistent-others -array-add '{ "tile-data" = {}; "tile-type"="small-spacer-tile"; }' && \
killall Dock`

**Add a Stack Folder with no name and full space**
(Modification of "Add a Stack with Recent Applications")
`defaults write com.apple.dock persistent-others -array-add '{ "tile-data" = {}; "tile-type"="spacer-tile"; }' && \
killall Dock
`

"small-spacer-tile" thanks to: [Click Here](http://bit.ly/2tLOwqH)

I tested it on iMac, macOS 10.12.5

**Comment by herrbischoff** [comment]
Thanks for the suggestions. But please, just please, don't use link shorteners like bit.ly for URLs. It's just bad form to obfuscate links and track the clicks. Only people who actually *want* to be opaque do that.
