### ISSUE TITLE
Tips + Request

### ISSUE THREAD

**Issue by forthrin** [herrbischoff/awesome-macos-command-line#183]
What a great page! I like to see a solution to how you can make changes like this take effect (and change in the Preferences GUI) without having to log out or reboot the computer.

    defaults write ~/Library/Preferences/.GlobalPreferences.plist com.apple.swipescrolldirection -bool NO
    sudo defaults write /var/db/locationd/Library/Preferences/ByHost/com.apple.locationd.plist LocationServicesEnabled -bool NO

**Comment by herrbischoff** [comment]
This is not a request service. I will leave this issue open for the next couple of weeks and will close it of no one steps forward with a suggestion. Which, given your request, I would not expect to be anyone.

**Comment by twilsonco** [comment]
Howabout a terminal command to enable/disable TM backups while on battery power? Something to actually change the built-in setting for whether or not TM backups run while on battery, rather than a hack to enable/disable TM backups in general based on power status.

**Comment by herrbischoff** [comment]
Simple:

```bash
sudo defaults write /Library/Preferences/com.apple.TimeMachine RequiresACPower -bool true
```

**Comment by herrbischoff** [comment]
https://github.com/herrbischoff/awesome-macos-command-line/commit/a5c05ad71e64d33f7577de06ed6a1b67bde01a9d
